### ISSUE TITLE
Cannot run program "Rscript"

### ISSUE THREAD

**Issue by nik01010** [biouno/r-plugin#1]
Hi,
I'm getting the below issue when trying to use the R Plugin for Jenkins.
Can you advise how to resolve this please?

Started by user admin
Running as SYSTEM
Building in workspace C:\Program Files (x86)\Jenkins\workspace\Test
[Test] $ Rscript C:\Windows\TEMP\jenkins1456748976511558414.R
The system cannot find the file specified
FATAL: command execution failed
java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
Caused: java.io.IOException: Cannot run program "Rscript" (in directory "C:\Program Files (x86)\Jenkins\workspace\Test"): CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(Unknown Source)
	at hudson.Proc$LocalProc.<init>(Proc.java:250)
	at hudson.Proc$LocalProc.<init>(Proc.java:219)
	at hudson.Launcher$LocalLauncher.launch(Launcher.java:937)
	at hudson.Launcher$ProcStarter.start(Launcher.java:455)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:109)
	at hudson.tasks.CommandInterpreter.perform(CommandInterpreter.java:66)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
	at hudson.model.Build$BuildExecution.build(Build.java:206)
	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:504)
	at hudson.model.Run.execute(Run.java:1815)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Execute R script' marked build as failure
Finished: FAILURE

**Comment by kinow** [comment]
Hi

You need to have that R executable in your Path environment variable for the Jenkins user.

It is normally done automatically on Windows when you use an installer.

I don't think it is a bug, so closing the issue. But feel free to comment here afterwards.

Cheers
Bruno

**Comment by nik01010** [comment]
Thanks for your response.
I had already tried adding the "C:\Program Files\R\R-3.6.1\bin" directory into the Windows Path Environment Variable, but that didn't fix the issue. If there is a specific requirement to set a Path variable in Jenkins in order for this plugin to work, please could you suggest what changes are needed exactly, as that would be helpful for users?

**Comment by kinow** [comment]
>what changes are needed exactly, as that would be helpful for users?

That's not easy @nik01010 , sorry. These changes vary depending on your operating system, how you are running Jenkins, what user you have, etc. I can definitely try to support (as volunteer) for issues with the plugin code.

You may have better luck with SO or Jenkins or Windows documentation. e.g. [How to set the PATH environment variable in Jenkins configuration on Windows?](https://stackoverflow.com/questions/36473479/how-to-set-the-path-environment-variable-in-jenkins-configuration-on-windows/36502958).

Note that the Path env var used must be defined for the user running Jenkins (in case you have a daemon/service). And also that if you define an environment variable, after Jenkins is running, it won't detect the change. You will need to restart the service correctly (i.e. if running in a terminal, better close re-open). 

But again, it may vary depending on your OS, user, and other settings.

Bruno

**Comment by kinow** [comment]
ps: the user mailing list or Jenkins JIRA (with r-plugin component) are better places for queries like this, as other users can chime in and answer, or you can check the archives for similar questions.
